### ISSUE TITLE
Stall or deadlock putting to DB in HintBPTSparseIdxMode

### ISSUE THREAD

**Issue by anacrolix** [nutsdb/nutsdb#303]
**Describe the bug**
When Putting a lot of entries in HintBPTSparseIdxMode mode, nutsdb abrubtly stalls.

**To Reproduce**
Steps to reproduce the behavior(Be specific!):
I put some 2.2 billion entries (bitmaps committed correspond to a `tx.Put`).
```
godo: starting dht-indexer
2023-03-08T00:04:22+1100 NIL [github.com/anacrolix/envpprof.startHTTP:75]: (pid=2869) envpprof serving http://127.0.0.1:6061
[2023-03-07T13:04:22Z INFO  dht_indexer::extension_init] [dht-indexer] initialized
2023-03-08T00:04:22+1100 NIL [github.com/anacrolix/dht-indexer.OpenDataDb:43]: loaded dht-indexer sqlite extension
2023/03/08 00:06:55 populate.go:230: committing 200087 bitmaps
2023/03/08 05:15:54 populate.go:262: committed 200087 bitmaps (10 MB) (deleted 193636)
2023/03/08 05:23:44 populate.go:230: committing 200713 bitmaps
2023/03/08 05:23:52 populate.go:262: committed 200713 bitmaps (10 MB) (deleted 197519)
2023/03/08 05:31:22 populate.go:230: committing 200006 bitmaps
2023/03/08 05:31:29 populate.go:262: committed 200006 bitmaps (10 MB) (deleted 199684)
2023/03/08 05:37:09 populate.go:230: committing 200607 bitmaps
2023/03/08 05:37:15 populate.go:262: committed 200607 bitmaps (10 MB) (deleted 200379)
2023/03/08 05:45:51 populate.go:230: committing 213400 bitmaps
2023/03/08 05:45:58 populate.go:262: committed 213400 bitmaps (11 MB) (deleted 212451)
2023/03/08 05:52:22 populate.go:230: committing 200309 bitmaps
2023/03/08 05:52:29 populate.go:262: committed 200309 bitmaps (10 MB) (deleted 199940)
2023/03/08 05:59:33 populate.go:230: committing 200074 bitmaps
2023/03/08 05:59:40 populate.go:262: committed 200074 bitmaps (11 MB) (deleted 199323)
2023/03/08 06:01:36 populate.go:104: processed 100000 docs
2023/03/08 06:06:51 populate.go:230: committing 201986 bitmaps
2023/03/08 06:06:58 populate.go:262: committed 201986 bitmaps (11 MB) (deleted 199952)
2023/03/08 06:13:57 populate.go:230: committing 200011 bitmaps
2023/03/08 06:14:04 populate.go:262: committed 200011 bitmaps (11 MB) (deleted 199350)
2023/03/08 06:20:50 populate.go:230: committing 205799 bitmaps
2023/03/08 06:20:57 populate.go:262: committed 205799 bitmaps (11 MB) (deleted 205608)
2023/03/08 06:26:47 populate.go:230: committing 200109 bitmaps
2023/03/08 06:26:54 populate.go:262: committed 200109 bitmaps (12 MB) (deleted 189117)
2023/03/08 06:33:40 populate.go:230: committing 200133 bitmaps
```

I opened like this:
```
	opts := nutsdb.DefaultOptions
	opts.EntryIdxMode = nutsdb.HintBPTSparseIdxMode
	opts.RWMode = nutsdb.MMap
	db, err := nutsdb.Open(opts, nutsdb.WithDir(path))
```

I put like this:
```
func (n nutsdbStorage) WriteBitmaps(ctx context.Context, bms map[string][]byte) (err error) {
	return n.db.Update(func(tx *nutsdb.Tx) error {
		for key, value := range bms {
			err := tx.Put(bitmapsBucket, []byte(key), value, 0)
			if err != nil {
				return err
			}
		}
		return nil
	})
}
```

**Expected behavior**
No stall.

**What actually happens**
It stalls.

**Screenshots**

**please complete the following information :**
 - OS: MacOS Ventura 13.2.1
 - NutsDB Version github.com/nutsdb/nutsdb v0.12.0

**Additional context**
Here are stack traces,

Just after it stalled:
```
goroutine 1 [sync.RWMutex.RLock, 11 minutes]:
sync.runtime_SemacquireRWMutexR(0x0?, 0xc0?, 0xc07f7a6120?)
	/Users/anacrolix/src/go1.20/src/runtime/sema.go:82 +0x26
sync.(*RWMutex).RLock(...)
	/Users/anacrolix/src/go1.20/src/sync/rwmutex.go:71
github.com/nutsdb/nutsdb.(*Tx).lock(0xc0001be000?)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/tx.go:622 +0x45
github.com/nutsdb/nutsdb.(*DB).Begin(0xc0001be000, 0x1?)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/tx.go:91 +0x3e
github.com/nutsdb/nutsdb.(*DB).managed(0xc005614aa0?, 0x96?, 0xc005614a78)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/db.go:997 +0x39
github.com/nutsdb/nutsdb.(*DB).View(...)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/db.go:310
github.com/anacrolix/dht-indexer/caterwaul.nutsdbStorage.GetBitmap({0xc0001be000?, {0xc000094a80?, 0xc000010168?}}, {0xc049b7b552?, 0x100012a87?})

goroutine 163901 [runnable]:
github.com/nutsdb/nutsdb.enqueue(...)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/bptree.go:170
github.com/nutsdb/nutsdb.(*BPTree).WriteNodes(0xc00019b260, 0xc06cd4f9c0?, 0xe5?, 0xc000010160?)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/bptree.go:346 +0x276
github.com/nutsdb/nutsdb.(*Tx).rotateActiveFile(0xc006187140)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/tx.go:527 +0x156
github.com/nutsdb/nutsdb.(*Tx).Commit(0xc006187140)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/tx.go:194 +0x318
github.com/nutsdb/nutsdb.(*DB).managed(0x1000184f7?, 0x0?, 0xc06cd4fcc0)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/db.go:1015 +0xaf
github.com/nutsdb/nutsdb.(*DB).Update(...)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/db.go:301
github.com/anacrolix/dht-indexer/caterwaul.nutsdbStorage.WriteBitmaps({0xc0001be000?, {0xc000094a80?, 0xc000010168?}}, {0x0?, 0xc04c77d2c0?}, 0xc073b9f0e0?)
	/Users/anacrolix/go/src/github.com/anacrolix/dht-indexer/caterwaul/nutsdb-storage.go:45 +0x49
github.com/anacrolix/dht-indexer/caterwaul.(*populator).commitBitmaps(0xc0001bc2a0, {0x1016a98f0, 0xc0000a9bc0}, 0xc04c77d2c0)
```

After SIGQUIT, 9 hours later:
```
\SIGQUIT: quit
PC=0x7ff80855811a m=0 sigcode=0

goroutine 1 [sync.RWMutex.RLock, 161 minutes]:
runtime.gopark(0xbb2ca1c7a7290640?, 0xfa98b7ca58beb0bd?, 0x80?, 0x87?, 0xbb2ca1c7a7290640?)
	/Users/anacrolix/src/go1.20/src/runtime/proc.go:381 +0xd6 fp=0xc0005588a8 sp=0xc000558888 pc=0x10003edb6
runtime.goparkunlock(...)
	/Users/anacrolix/src/go1.20/src/runtime/proc.go:387
runtime.semacquire1(0xc0002801bc, 0x0?, 0x3, 0x0, 0x60?)
	/Users/anacrolix/src/go1.20/src/runtime/sema.go:160 +0x20f fp=0xc000558910 sp=0xc0005588a8 pc=0x1000500cf
sync.runtime_SemacquireRWMutexR(0x0?, 0x80?, 0xc072616720?)
	/Users/anacrolix/src/go1.20/src/runtime/sema.go:82 +0x26 fp=0xc000558948 sp=0xc000558910 pc=0x10006ede6
sync.(*RWMutex).RLock(...)
	/Users/anacrolix/src/go1.20/src/sync/rwmutex.go:71
github.com/nutsdb/nutsdb.(*Tx).lock(0xc0002800f0?)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/tx.go:622 +0x45 fp=0xc000558970 sp=0xc000558948 pc=0x100ef6225
github.com/nutsdb/nutsdb.(*DB).Begin(0xc0002800f0, 0x1?)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/tx.go:91 +0x3e fp=0xc0005589a8 sp=0xc000558970 pc=0x100ef223e
github.com/nutsdb/nutsdb.(*DB).managed(0xc0516b2180?, 0x38?, 0xc000558a40)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/db.go:997 +0x39 fp=0xc000558a08 sp=0xc0005589a8 pc=0x100eed4b9
github.com/nutsdb/nutsdb.(*DB).View(...)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/db.go:310
github.com/anacrolix/dht-indexer/caterwaul.nutsdbStorage.GetBitmap({0xc0002800f0?, {0xc0001120c0?, 0xc000124060?}}, {0xc056703580?, 0x100012307?})
	/Users/anacrolix/go/src/github.com/anacrolix/dht-indexer/caterwaul/nutsdb-storage.go:36 +0x87 fp=0xc000558a70 sp=0xc000558a08 pc=0x100f28487
github.com/anacrolix/dht-indexer/caterwaul.(*nutsdbStorage).GetBitmap(0x1012abf20?, {0xc056703580?, 0xc056703580?})
	<autogenerated>:1 +0x46 fp=0xc000558aa8 sp=0xc000558a70 pc=0x100f33266
github.com/anacrolix/dht-indexer/caterwaul.(*populator).getBitmap(0xc03d77a000, {0xc03da10700?, 0xc03da10700?}, {0xc056703580, 0x6})

goroutine 163956 [runnable]:
runtime.asyncPreempt2()
	/Users/anacrolix/src/go1.20/src/runtime/preempt.go:307 +0x3f fp=0xc042913780 sp=0xc042913760 pc=0x10003d4bf
runtime.asyncPreempt()
	/Users/anacrolix/src/go1.20/src/runtime/preempt_amd64.s:53 +0xde fp=0xc042913908 sp=0xc042913780 pc=0x100074fde
github.com/nutsdb/nutsdb.enqueue(...)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/bptree.go:170
github.com/nutsdb/nutsdb.(*BPTree).WriteNodes(0xc0001de070, 0x12f000000?, 0xc0?, 0x100ef176e?)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/bptree.go:346 +0x276 fp=0xc042913980 sp=0xc042913908 pc=0x100ee2b96
github.com/nutsdb/nutsdb.(*Tx).rotateActiveFile(0xc0526cbcc0)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/tx.go:527 +0x156 fp=0xc042913a20 sp=0xc042913980 pc=0x100ef5ab6
github.com/nutsdb/nutsdb.(*Tx).Commit(0xc0526cbcc0)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/tx.go:194 +0x318 fp=0xc042913c48 sp=0xc042913a20 pc=0x100ef2758
github.com/nutsdb/nutsdb.(*DB).managed(0x100017d77?, 0x0?, 0xc0136ffcc0)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/db.go:1015 +0xaf fp=0xc042913ca8 sp=0xc042913c48 pc=0x100eed52f
github.com/nutsdb/nutsdb.(*DB).Update(...)
	/Users/anacrolix/go/pkg/mod/github.com/nutsdb/nutsdb@v0.12.0/db.go:301
github.com/anacrolix/dht-indexer/caterwaul.nutsdbStorage.WriteBitmaps({0xc0002800f0?, {0xc0001120c0?, 0xc000124060?}}, {0x0?, 0xc0305b3bf0?}, 0xc089fbc2e0?)
	/Users/anacrolix/go/src/github.com/anacrolix/dht-indexer/caterwaul/nutsdb-storage.go:45 +0x49 fp=0xc042913ce0 sp=0xc042913ca8 pc=0x100f28609
github.com/anacrolix/dht-indexer/caterwaul.(*nutsdbStorage).WriteBitmaps(0xc0136ffec8?, {0x1016a9630?, 0xc000284a80?}, 0x5?)
	<autogenerated>:1 +0x4e fp=0xc042913d20 sp=0xc042913ce0 pc=0x100f333ae
github.com/anacrolix/dht-indexer/caterwaul.(*populator).commitBitmaps(0xc03d77a000, {0x1016a9630, 0xc000284a80}, 0xc0305b3bf0)

rax    0x104
rbx    0x7ff84bed1680
rcx    0x7ff7bfefef08
rdx    0x1000
rdi    0x102285de0
rsi    0x110100001200
rbp    0x7ff7bfefefb0
rsp    0x7ff7bfefef08
r8     0x0
r9     0xa0
r10    0x0
r11    0x246
r12    0x16
r13    0x0
r14    0x110100001200
r15    0x1000
rip    0x7ff80855811a
rflags 0x247
cs     0x7
fs     0x0
gs     0x0

real	551m39.569s
user	302m18.661s
sys	79m23.374s
```

Note that in the other modes, HintKeyAndRAMIdxMode and HintKeyValAndRAMIdxMode, it is fine, but uses too much memory so I'm trying the sparse mode.

**Comment by xujiajun** [comment]
hi,  I tried your way to write but haven't reproduced the problem, but I can give you some advice.
> I opened like this:
> 
> ```
> 	opts := nutsdb.DefaultOptions
> 	opts.EntryIdxMode = nutsdb.HintBPTSparseIdxMode
> 	opts.RWMode = nutsdb.MMap
> 	db, err := nutsdb.Open(opts, nutsdb.WithDir(path))
> ```

you can turn off sync to speed up writing:

```go
	start := time.Now()
	opts := nutsdb.DefaultOptions
	opts.EntryIdxMode = nutsdb.HintBPTSparseIdxMode
	opts.RWMode = nutsdb.MMap
	opts.SyncEnable = false // turn off sync
```

> I put like this:
> 
> ```
> func (n nutsdbStorage) WriteBitmaps(ctx context.Context, bms map[string][]byte) (err error) {
> 	return n.db.Update(func(tx *nutsdb.Tx) error {
> 		for key, value := range bms {
> 			err := tx.Put(bitmapsBucket, []byte(key), value, 0)
> 			if err != nil {
> 				return err
> 			}
> 		}
> 		return nil
> 	})
> }
> ```
 
Are you directly writing all the data in a loop? It is recommended to write in batches. 

The example below equals 1000 entries as one transaction:
```go
end := 1000
	for j := 1; j <= end; j++ {
		if err := db.Update(
			func(tx *nutsdb.Tx) error {
				for i := (j - 1) * 1000; i < j*1000; i++ {
					key := []byte("key" + strconv2.IntToStr(i))
					val := []byte("value" + strconv2.IntToStr(i))
					if err := tx.Put(bitmapsBucket, key, val, 0); err != nil {
						return err
					}
				}
				return nil
			}); err != nil {
			panic(err)
		} else {
			fmt.Println("ok batch :", j)
		}
	}
```

**Comment by anacrolix** [comment]
If it helps, it's interesting that it always stalls at around 2.1GiB of data (in a single transaction as you pointed out). That seems remarkably like an integer overflow of some kind.

**Comment by anacrolix** [comment]
I'm not able to reproduce it myself anymore, I'll close the issue when I confirm it.

I did find that HintBPTSparseIdxMode wasn't sufficient to reduce memory load on loading a database, so I may have to use an alternative database implementation.

Thanks!

**Comment by xujiajun** [comment]
> I'm not able to reproduce it myself anymore, I'll close the issue when I confirm it.
> 
> I did find that HintBPTSparseIdxMode wasn't sufficient to reduce memory load on loading a database, so I may have to use an alternative database implementation.
> 
> Thanks!

ok got it, sorry nutsdb didn't help you

**Comment by anacrolix** [comment]
Sorry I can still reproduce it, I had accidentally changed the mode back to `HintKeyAndRAMIdxMode` in testing. When I set `SyncEnable = false`, it happens almost right away.

The CPU is flat out, here's a profile:
![image](https://user-images.githubusercontent.com/988750/224861900-22f4886f-adbc-4126-a8aa-b82ed67eb4ed.png)

My batch size is 200k, I haven't tried reducing it as it would require reworking a lot of logic.

**Comment by xujiajun** [comment]
At first it was HintBPTSparseIdxMode, and then switched to HintKeyAndRAMIdxMode later? this is not allowed.
BTW your batch size is 200k, it‘s a big transaction.

**Comment by anacrolix** [comment]
No it's just HintBPTSparseIdxMode. I mean that when I said I couldn't reproduce it anymore it's because I had accidently started using the other mode. It's definitely reproducible with HintBPTSparseIdxMode, starting with a fresh directory.

**Comment by xujiajun** [comment]
ok. I see.

**Comment by elliotchenzichang** [comment]
We already deleted this mode. Please use other modes to store your data. Thanks!
